# Generated by Django 6.0.5 on 2026-05-22 14:03

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DayMeta",
            fields=[
                ("date", models.DateField(primary_key=True, serialize=False)),
                ("n_candidates", models.IntegerField()),
                ("n_themes", models.IntegerField()),
                ("top_theme", models.CharField(blank=True, max_length=128)),
                ("theme_counts", models.JSONField(default=dict)),
                ("parquet_mtime", models.FloatField()),
                ("rebuilt_at", models.DateTimeField()),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="Brief",
            fields=[
                (
                    "pk",
                    models.CompositePrimaryKey(
                        "date",
                        "ticker",
                        blank=True,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date", models.DateField(db_index=True)),
                ("ticker", models.CharField(max_length=12)),
                ("theme", models.CharField(db_index=True, max_length=128)),
                ("company_name", models.CharField(max_length=256)),
                ("rationale", models.TextField(blank=True)),
                ("gemini_confidence", models.FloatField(blank=True, null=True)),
                ("market_cap", models.FloatField(blank=True, null=True)),
                ("gates_passed", models.JSONField(blank=True, default=list)),
                ("n_gates_passed", models.IntegerField(default=0)),
                ("gates_failed", models.JSONField(blank=True, default=list)),
                ("n_gates_failed", models.IntegerField(default=0)),
                ("gates_unknown", models.JSONField(blank=True, default=list)),
                ("n_gates_unknown", models.IntegerField(default=0)),
                ("verified", models.BooleanField(default=False)),
                ("source_event_url", models.URLField(blank=True, max_length=2048)),
                ("source_event_title", models.CharField(blank=True, max_length=512)),
                ("source_event_published_at", models.CharField(blank=True, max_length=64)),
                ("theme_search_keywords", models.JSONField(blank=True, default=list)),
                ("industry_id", models.FloatField(blank=True, null=True)),
                ("industry_name", models.CharField(blank=True, max_length=256)),
                ("sector_name", models.CharField(blank=True, max_length=128)),
                ("insider_score_usd", models.FloatField(blank=True, null=True)),
                ("insider_score_sector_percentile", models.FloatField(blank=True, null=True)),
                ("fcff_yield_pct", models.FloatField(blank=True, null=True)),
                ("fcff_yield_sector_percentile", models.FloatField(blank=True, null=True)),
                ("valuation_pe", models.FloatField(blank=True, null=True)),
                ("valuation_ps", models.FloatField(blank=True, null=True)),
                ("valuation_ev_rev", models.FloatField(blank=True, null=True)),
                ("valuation_ev_ebitda", models.FloatField(blank=True, null=True)),
                ("valuation_fcf_margin", models.FloatField(blank=True, null=True)),
                ("valuation_composite_sector_percentile", models.FloatField(blank=True, null=True)),
                ("valuation_financials_publish_date", models.CharField(blank=True, max_length=32)),
                ("valuation_financials_age_days", models.IntegerField(blank=True, null=True)),
                ("roic_pct", models.FloatField(blank=True, null=True)),
                ("roe_pct", models.FloatField(blank=True, null=True)),
                ("magic_formula_health_pass", models.BooleanField(default=False)),
                ("technical_rsi", models.FloatField(blank=True, null=True)),
                ("technical_ma50_distance_pct", models.FloatField(blank=True, null=True)),
                ("technical_atr_pct", models.FloatField(blank=True, null=True)),
                ("technical_volume_zscore", models.FloatField(blank=True, null=True)),
                ("technical_pct_off_52w_high", models.FloatField(blank=True, null=True)),
                ("technical_pct_off_52w_low", models.FloatField(blank=True, null=True)),
                ("technical_ma200_distance_pct", models.FloatField(blank=True, null=True)),
                ("technical_ma200_slope_pct_per_day", models.FloatField(blank=True, null=True)),
                ("catalyst_strength", models.FloatField(blank=True, null=True)),
                ("catalyst_event_type", models.CharField(blank=True, max_length=64)),
                ("catalyst_confidence", models.FloatField(blank=True, null=True)),
                ("magic_formula_rank", models.FloatField(blank=True, null=True)),
                ("magic_formula_cohort_n", models.IntegerField(blank=True, null=True)),
                ("deep_drawdown_reversal", models.BooleanField(default=False)),
                ("layer4_weighted_score", models.IntegerField(default=0)),
                ("also_in_themes", models.JSONField(blank=True, default=list)),
                ("rank_in_day", models.IntegerField(blank=True, null=True)),
                ("cohort_size_in_day", models.IntegerField(blank=True, null=True)),
                ("next_earnings_date", models.DateField(blank=True, null=True)),
                ("brief_model_used", models.CharField(blank=True, max_length=64)),
                ("brief_tldr", models.TextField(blank=True)),
                ("brief_supply_chain_md", models.TextField(blank=True)),
                ("brief_bear_summary_md", models.TextField(blank=True)),
                ("brief_catalyst_failure_exit", models.TextField(blank=True)),
                ("brief_entry_price_note", models.TextField(blank=True)),
                ("brief_position_pct", models.FloatField(blank=True, null=True)),
                ("brief_time_exit_weeks", models.IntegerField(blank=True, null=True)),
                (
                    "brief_time_exit_on_catalyst_failure_weeks",
                    models.IntegerField(blank=True, null=True),
                ),
                ("brief_disaster_stop_pct", models.FloatField(blank=True, null=True)),
                ("brief_full_md", models.TextField(blank=True)),
                ("brief_generated_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-date", "-layer4_weighted_score", "ticker"],
                "indexes": [
                    models.Index(
                        fields=["-date", "-layer4_weighted_score"], name="brief_date_score_idx"
                    ),
                    models.Index(fields=["ticker"], name="brief_ticker_idx"),
                ],
            },
        ),
    ]
