# Generated by Django 6.0.5 on 2026-05-24 09:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("briefs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="brief",
            name="peer_cohort_level",
            field=models.CharField(blank=True, default="", max_length=8),
        ),
    ]
