# Generated by Django 6.0.5 on 2026-05-26 11:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("briefs", "0002_brief_peer_cohort_level"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="brief",
            name="brief_full_md",
        ),
    ]
