# Generated by Django 6.0.5 on 2026-05-27 11:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("briefs", "0003_remove_brief_brief_full_md"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="brief",
            name="brief_disaster_stop_pct",
        ),
        migrations.RemoveField(
            model_name="brief",
            name="brief_entry_price_note",
        ),
        migrations.RemoveField(
            model_name="brief",
            name="brief_position_pct",
        ),
        migrations.RemoveField(
            model_name="brief",
            name="brief_time_exit_on_catalyst_failure_weeks",
        ),
        migrations.RemoveField(
            model_name="brief",
            name="brief_time_exit_weeks",
        ),
        migrations.AddField(
            model_name="brief",
            name="brief_trade_setup",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
