# Generated by Django 6.0.5 on 2026-05-31 08:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("briefs", "0004_remove_brief_brief_disaster_stop_pct_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="brief",
            name="brief_template_facts",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="brief",
            name="brief_template_id",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
    ]
