# Generated by Django 6.0.5 on 2026-05-31 09:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("briefs", "0005_brief_brief_template_facts_brief_brief_template_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="brief",
            name="brief_template_id",
            field=models.CharField(blank=True, default="", max_length=128),
        ),
    ]
