# Generated by Django 6.0.5 on 2026-05-31 09:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("briefs", "0006_alter_brief_brief_template_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="brief",
            old_name="gemini_confidence",
            new_name="llm_confidence",
        ),
    ]
