# Generated by Django 6.0.6 on 2026-06-11 17:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("briefs", "0007_rename_gemini_confidence_llm_confidence"),
    ]

    operations = [
        migrations.AddField(
            model_name="brief",
            name="gate_verdict_json",
            field=models.TextField(blank=True, default=""),
        ),
    ]
