# Generated by Django 6.0.6 on 2026-06-12 08:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("briefs", "0008_brief_gate_verdict_json"),
    ]

    operations = [
        migrations.AddField(
            model_name="brief",
            name="buffett_data_coverage",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="brief",
            name="buffett_margin_of_safety_pct",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="brief",
            name="buffett_owner_earnings_yield_pct",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="brief",
            name="buffett_quality_score",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="brief",
            name="buffett_roic_3y_avg",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="brief",
            name="buffett_roic_latest",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
