# Generated by Django 6.0.6 on 2026-06-12 10:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("briefs", "0009_brief_buffett_data_coverage_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="brief",
            name="buffett_management_candor",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name="brief",
            name="buffett_moat_trend",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name="brief",
            name="buffett_moat_type",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name="brief",
            name="buffett_qual_computed_at",
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name="brief",
            name="buffett_qualitative_rationale",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="brief",
            name="buffett_understandable",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="brief",
            name="buffett_used_scuttlebutt",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
