# Generated by Django 6.0.6 on 2026-06-13 16:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("briefs", "0010_brief_buffett_management_candor_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="brief",
            name="expert_assessments",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
