# Generated by Django 6.0.6 on 2026-06-13 18:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("briefs", "0011_brief_expert_assessments"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="brief",
            name="buffett_data_coverage",
        ),
        migrations.RemoveField(
            model_name="brief",
            name="buffett_management_candor",
        ),
        migrations.RemoveField(
            model_name="brief",
            name="buffett_margin_of_safety_pct",
        ),
        migrations.RemoveField(
            model_name="brief",
            name="buffett_moat_trend",
        ),
        migrations.RemoveField(
            model_name="brief",
            name="buffett_moat_type",
        ),
        migrations.RemoveField(
            model_name="brief",
            name="buffett_owner_earnings_yield_pct",
        ),
        migrations.RemoveField(
            model_name="brief",
            name="buffett_qual_computed_at",
        ),
        migrations.RemoveField(
            model_name="brief",
            name="buffett_qualitative_rationale",
        ),
        migrations.RemoveField(
            model_name="brief",
            name="buffett_quality_score",
        ),
        migrations.RemoveField(
            model_name="brief",
            name="buffett_roic_3y_avg",
        ),
        migrations.RemoveField(
            model_name="brief",
            name="buffett_roic_latest",
        ),
        migrations.RemoveField(
            model_name="brief",
            name="buffett_understandable",
        ),
        migrations.RemoveField(
            model_name="brief",
            name="buffett_used_scuttlebutt",
        ),
    ]
