# Generated by Django 6.0.6 on 2026-06-17 13:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("briefs", "0012_remove_brief_buffett_data_coverage_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="brief",
            name="insider_signal_version",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
    ]
