# Generated by Django 6.0.6 on 2026-06-25 12:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("briefs", "0013_brief_insider_signal_version"),
    ]

    operations = [
        migrations.AddField(
            model_name="brief",
            name="atr_penalty",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="brief",
            name="scorer_config_version",
            field=models.CharField(blank=True, default="", max_length=128),
        ),
        migrations.AddField(
            model_name="brief",
            name="selection_score",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
