# Generated by Django 6.0.6 on 2026-07-05 15:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("briefs", "0014_brief_selection_score"),
    ]

    operations = [
        migrations.AddField(
            model_name="brief",
            name="market_state",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
        migrations.AddField(
            model_name="brief",
            name="market_state_atr_pct",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="brief",
            name="market_state_atr_pct_q",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="brief",
            name="market_state_config_version",
            field=models.CharField(blank=True, default="", max_length=128),
        ),
        migrations.AddField(
            model_name="brief",
            name="market_state_dist200",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="brief",
            name="market_state_squeeze_on",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="brief",
            name="market_state_vix",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="brief",
            name="market_state_vix_decile",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
