# Generated by Django 6.0.7 on 2026-07-28 11:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("briefs", "0015_brief_market_state_brief_market_state_atr_pct_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="brief",
            name="brief_error_kind",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="brief",
            name="brief_status",
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
