# Generated by Django 6.0.7 on 2026-08-20 16:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("briefs", "0016_brief_brief_error_kind_brief_brief_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="brief",
            name="brief_causal_support",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="brief",
            name="brief_channel_grounding",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="brief",
            name="brief_support_guard_status",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="brief",
            name="channel_evidence",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="brief",
            name="channel_falsifier",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="brief",
            name="channel_grounding_quote",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="brief",
            name="channel_grounding_reason",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="brief",
            name="channel_text",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="brief",
            name="channel_type",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
    ]
