# Generated by Django 6.0.8 on 2026-09-06 12:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("briefs", "0017_brief_brief_causal_support_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="brief",
            name="event_arrival_session",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="brief",
            name="event_buyers",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="brief",
            name="event_cluster_usd",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="brief",
            name="event_filing_lag_bdays",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="brief",
            name="event_gate_version",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="brief",
            name="event_n_insiders",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="brief",
            name="event_overlap",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="brief",
            name="source",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
    ]
