#!/usr/bin/env python
"""Phase-2/3 outcome join + inference for the Stage-1 retro gate-increment study.

Joins the Phase-1 blind labels (hash-pinned, generated by
``stage1_retro_label_pairs.py``) to the stored population-ladder outcomes and
runs the single pre-registered primary hypothesis test, per
`docs/research/stage1_retro_gate_increment_prereg_2026_08_19.md` (§8, §10-§12).

Locked parameters (pre-registered; do not change without a memo amendment):

* **Two-stage commit** — this script refuses to run unless the labels parquet
  sha256 equals the Stage-B committed value (``LABELS_SHA256``, pre-reg §11.2).
* **Primary (H1, CLEAN window only)** — one-sided KEPT − REFUSED > 0 on
  pair-cluster mean matured `market_excess_return`; matured = ``terminal``
  rows only; `market_excess_return` winsorized at 1% per leg (row-level,
  each leg separately; unwinsorized also reported); inference via a two-way
  (pair × brief-day) cluster bootstrap with 10,000 resamples.
* **Everything else is descriptive** — the DEV-window contrast, the
  ticker-level three-way split, the crowd-out share, and the refusal-reason
  taxonomy carry no hypothesis slot and no verdict vocabulary.
* **Power (Phase 3)** — one-sided two-sample normal-approximation power for
  the forward window, parameterized by the measured refusal rate and the
  CLEAN pair-level spread magnitude.

Usage::

    python apps/alphalens-research/scripts/stage1_retro_outcome_inference.py \\
        --labels <labels.parquet> \\
        --outcomes <ladder_outcomes.csv> \\
        --calls-log <phase1_calls.jsonl> \\
        --out <results.json>

The outcomes CSV is a read-only extract of
``~/.alphalens/population_ladders/<brief_date>.parquet`` rows for the cohort
window (columns: brief_date, ticker, terminal, matured_at,
market_excess_return, plannable, nonplannable_reason, ...).
"""

from __future__ import annotations

import argparse
import hashlib
import json
import math
import sys
from pathlib import Path

import numpy as np
import pandas as pd

# --- Locked constants (pre-reg §8, §10-§12) ---------------------------------

LABELS_SHA256 = "c8440d40a0c2751717b62f3a83ef2d245957c2a43cd55fbe3405ccdb25bfb95f"
BOOTSTRAP_RESAMPLES = 10_000
BOOTSTRAP_SEED = 20260819
WINSOR_PCT = 0.01
ALPHA_ONE_SIDED = 0.05
TARGET_POWER = 0.80
CONTRAST_LABELS = ("KEPT", "THEME_REFUSED")
KEPT = "KEPT"
REFUSED = "THEME_REFUSED"

# --- Refusal-reason taxonomy (descriptive heuristic, ordered rules) ---------
# Categories per the study plan: non-event rejection vs direction filter vs
# no-transmission-channel vs other. Ordered: event-ness is upstream of
# direction, which is upstream of channel existence.

NON_EVENT = "non_event"
DIRECTION = "direction_filter"
NO_CHANNEL = "no_channel"
OTHER = "other"

_NON_EVENT_CUES = (
    "commentary",
    "opinion",
    "forecast",
    "prediction",
    "round-up",
    "roundup",
    "speculative headline",
    "descriptive article",
    "descriptive financial news",
    "no actionable event",
    "no concrete event",
    "not an event",
    "vague",
    "figurative",
    "newsletter",
    "comparison article",
    "educational",
    "explanation of existing",
    "hypothetical",
    "recap",
    "listicle",
    "slogan",
)
_DIRECTION_CUES = (
    "adverse",
    "adversely",
    "victim",
    "would suffer",
    "harmed",
    "headwind",
    "negative for",
    "downside for",
)
_NO_CHANNEL_CUES = (
    "transmission channel",
    "beneficiary",
    "beneficiaries",
    "not material",
    "no material",
    "materially",
    "not u.s.-listed",
    "no u.s.-listed",
    "private company",
    "non-publicly-traded",
    "not publicly",
    "too small",
    "localized",
    "no direct",
    "no clear",
    "no identifiable",
    "no specific",
    "no public company",
)


def majority_bucket(buckets: list[str]) -> str:
    """Most frequent bucket; ties resolve alphabetically (set order is not
    deterministic across runs, and identical calls-log input must always
    yield identical taxonomy counts)."""
    return max(sorted(set(buckets)), key=buckets.count)


def classify_refusal_reason(reason: str | None) -> str:
    """Bucket a mapper decline reason. Heuristic, descriptive only."""
    if not reason or not reason.strip():
        return OTHER
    text = reason.lower()
    if any(cue in text for cue in _NON_EVENT_CUES):
        return NON_EVENT
    if any(cue in text for cue in _DIRECTION_CUES):
        return DIRECTION
    if any(cue in text for cue in _NO_CHANNEL_CUES):
        return NO_CHANNEL
    return OTHER


# --- Pure stats -------------------------------------------------------------


def winsorize(values: np.ndarray, pct: float = WINSOR_PCT) -> np.ndarray:
    """Clip values at the empirical [pct, 1-pct] quantiles."""
    arr = np.asarray(values, dtype=float)
    if arr.size == 0:
        return arr
    lo, hi = np.quantile(arr, [pct, 1.0 - pct])
    return np.clip(arr, lo, hi)


def pair_cluster_delta(rows: pd.DataFrame) -> tuple[float, pd.DataFrame]:
    """KEPT − REFUSED difference of unweighted means of pair-cluster means.

    ``rows`` needs columns ``pair_id``, ``pair_label`` (KEPT/THEME_REFUSED)
    and ``y``. Returns (delta, per-pair means frame).
    """
    pair_means = rows.groupby(["pair_label", "pair_id"], sort=True)["y"].mean().reset_index()
    leg = pair_means.groupby("pair_label")["y"].mean()
    delta = float(leg[KEPT] - leg[REFUSED])
    return delta, pair_means


def two_way_cluster_bootstrap(
    rows: pd.DataFrame,
    n_boot: int = BOOTSTRAP_RESAMPLES,
    seed: int = BOOTSTRAP_SEED,
) -> dict:
    """Two-way (pair × brief-day) cluster bootstrap of the KEPT − REFUSED delta.

    Each resample independently draws pairs and brief days with replacement;
    a row's weight is (times its pair was drawn) × (times its day was drawn).
    Pair-cluster means are day-weighted; leg means are pair-multiplicity
    weighted. Resamples where either leg has no represented pair are skipped
    and counted.
    """
    rng = np.random.default_rng(seed)
    pair_ids, pair_idx = np.unique(rows["pair_id"].to_numpy(), return_inverse=True)
    day_ids, day_idx = np.unique(rows["brief_date"].to_numpy(), return_inverse=True)
    y = rows["y"].to_numpy(dtype=float)
    n_pairs, n_days = len(pair_ids), len(day_ids)

    pair_is_kept = np.zeros(n_pairs, dtype=bool)
    for label, p_i in zip(rows["pair_label"].to_numpy(), pair_idx, strict=True):
        if label == KEPT:
            pair_is_kept[p_i] = True

    deltas = np.empty(n_boot, dtype=float)
    n_skipped = 0
    filled = 0
    while filled < n_boot:
        pair_mult = np.bincount(rng.integers(0, n_pairs, size=n_pairs), minlength=n_pairs)
        day_mult = np.bincount(rng.integers(0, n_days, size=n_days), minlength=n_days)
        w_day = day_mult[day_idx].astype(float)
        num = np.bincount(pair_idx, weights=w_day * y, minlength=n_pairs)
        den = np.bincount(pair_idx, weights=w_day, minlength=n_pairs)
        alive = (den > 0) & (pair_mult > 0)
        kept_alive = alive & pair_is_kept
        ref_alive = alive & ~pair_is_kept
        if not kept_alive.any() or not ref_alive.any():
            n_skipped += 1
            continue
        pmeans = np.zeros(n_pairs, dtype=float)
        pmeans[alive] = num[alive] / den[alive]
        w_pair = pair_mult.astype(float)
        kept_mean = np.average(pmeans[kept_alive], weights=w_pair[kept_alive])
        ref_mean = np.average(pmeans[ref_alive], weights=w_pair[ref_alive])
        deltas[filled] = kept_mean - ref_mean
        filled += 1

    p_one_sided = float(np.mean(deltas <= 0.0))
    ci_lo, ci_hi = np.quantile(deltas, [0.025, 0.975])
    return {
        "n_resamples": n_boot,
        "n_skipped_empty_leg": n_skipped,
        "p_one_sided_gt0": p_one_sided,
        "ci95": [float(ci_lo), float(ci_hi)],
        "boot_mean": float(np.mean(deltas)),
        "boot_sd": float(np.std(deltas, ddof=1)),
    }


def _norm_cdf(x: float) -> float:
    return 0.5 * (1.0 + math.erf(x / math.sqrt(2.0)))


def _norm_ppf(q: float) -> float:
    # Bisection is plenty for the few calls made here.
    lo, hi = -10.0, 10.0
    for _ in range(200):
        mid = (lo + hi) / 2.0
        if _norm_cdf(mid) < q:
            lo = mid
        else:
            hi = mid
    return (lo + hi) / 2.0


def power_one_sided(
    delta: float,
    sd: float,
    n_kept: float,
    n_refused: float,
    alpha: float = ALPHA_ONE_SIDED,
) -> float:
    """Normal-approximation power of a one-sided two-sample mean test."""
    if min(n_kept, n_refused) <= 0 or sd <= 0:
        return 0.0
    se = sd * math.sqrt(1.0 / n_kept + 1.0 / n_refused)
    z_alpha = _norm_ppf(1.0 - alpha)
    return _norm_cdf(delta / se - z_alpha)


def required_n_per_leg(
    delta: float,
    sd: float,
    alpha: float = ALPHA_ONE_SIDED,
    power: float = TARGET_POWER,
) -> int:
    """Balanced per-leg n for a one-sided two-sample test (normal approx)."""
    if delta <= 0 or sd <= 0:
        raise ValueError("delta and sd must be positive")
    z = _norm_ppf(1.0 - alpha) + _norm_ppf(power)
    return math.ceil(2.0 * (z * sd / delta) ** 2)


# --- Assembly ---------------------------------------------------------------


def _contrast_stats(matured: pd.DataFrame, winsor: bool) -> dict:
    rows = matured.copy()
    if winsor:
        rows["y"] = np.nan
        for label in CONTRAST_LABELS:
            leg_mask = rows["pair_label"] == label
            rows.loc[leg_mask, "y"] = winsorize(
                rows.loc[leg_mask, "market_excess_return"].to_numpy()
            )
    else:
        rows["y"] = rows["market_excess_return"]
    delta, pair_means = pair_cluster_delta(rows)
    boot = two_way_cluster_bootstrap(rows)
    legs = {}
    for label in CONTRAST_LABELS:
        leg_pairs = pair_means[pair_means["pair_label"] == label]["y"]
        leg_rows = rows[rows["pair_label"] == label]
        legs[label] = {
            "n_pairs": len(leg_pairs),
            "n_rows": len(leg_rows),
            "n_brief_days": int(leg_rows["brief_date"].nunique()),
            "pair_mean": float(leg_pairs.mean()),
            "pair_sd": float(leg_pairs.std(ddof=1)),
            "row_mean": float(leg_rows["y"].mean()),
        }
    return {"winsorized": winsor, "delta": delta, "legs": legs, "bootstrap": boot}


def _attrition(joined: pd.DataFrame, window: str) -> dict:
    win = joined[joined["window"] == window]
    contrast = win[win["pair_label"].isin(CONTRAST_LABELS)]
    terminal = contrast["terminal"].fillna(False).astype(bool)
    nonterminal = contrast[~terminal]
    plannable = nonterminal["plannable"].fillna(False).astype(bool)
    return {
        "rows_total": len(win),
        "rows_in_contrast_pairs": len(contrast),
        "rows_matured_used": int((terminal & contrast["market_excess_return"].notna()).sum()),
        "rows_ongoing_plannable_excluded": int(plannable.sum()),
        "rows_nonplannable_never_matured_excluded": int((~plannable).sum()),
        "rows_instrument_failure": int((win["pair_label"] == "INSTRUMENT_FAILURE").sum()),
        "rows_no_source_event": int((win["pair_label"] == "NO_SOURCE_EVENT").sum()),
    }


def _matured_contrast(joined: pd.DataFrame, window: str) -> pd.DataFrame:
    sub = joined[
        (joined["window"] == window)
        & joined["pair_label"].isin(CONTRAST_LABELS)
        & (joined["terminal"] == True)  # noqa: E712
        & joined["market_excess_return"].notna()
    ]
    return sub[["pair_id", "pair_label", "brief_date", "market_excess_return"]].copy()


def _refusal_taxonomy(calls_log: Path) -> dict:
    per_pair: dict[str, list[str]] = {}
    examples: dict[str, list[str]] = {NON_EVENT: [], DIRECTION: [], NO_CHANNEL: [], OTHER: []}
    with calls_log.open(encoding="utf-8") as fh:
        for line in fh:
            rec = json.loads(line)
            if rec.get("call_label") != REFUSED:
                continue
            reason = rec.get("no_candidates_reason") or ""
            bucket = classify_refusal_reason(reason)
            per_pair.setdefault(rec["pair_id"], []).append(bucket)
            if reason and len(examples[bucket]) < 5:
                examples[bucket].append(reason.strip()[:240])
    pair_buckets = {pid: majority_bucket(buckets) for pid, buckets in per_pair.items()}
    counts: dict[str, int] = {}
    for bucket in pair_buckets.values():
        counts[bucket] = counts.get(bucket, 0) + 1
    return {
        "pair_majority_counts": counts,
        "n_pairs_with_declines": len(pair_buckets),
        "call_level_examples": examples,
        "pair_buckets": pair_buckets,
    }


def _crowd_out(labels: pd.DataFrame) -> dict:
    kept_rows = labels[labels["pair_label"] == KEPT]
    split = kept_rows["row_label"].value_counts().to_dict()
    absent = int(split.get("KEPT_TICKER_ABSENT", 0))
    proposed = int(split.get("KEPT_TICKER_PROPOSED", 0))
    total = absent + proposed
    per_window = {}
    for window, grp in kept_rows.groupby("window"):
        a = int((grp["row_label"] == "KEPT_TICKER_ABSENT").sum())
        p = int((grp["row_label"] == "KEPT_TICKER_PROPOSED").sum())
        per_window[window] = {"absent": a, "proposed": p}
    return {
        "kept_rows": total,
        "ticker_absent": absent,
        "ticker_proposed": proposed,
        "crowd_out_share": (absent / total) if total else None,
        "per_window": per_window,
    }


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--labels", type=Path, required=True)
    parser.add_argument("--outcomes", type=Path, required=True)
    parser.add_argument("--calls-log", type=Path, required=True)
    parser.add_argument("--out", type=Path, required=True)
    args = parser.parse_args(argv)

    digest = hashlib.sha256(args.labels.read_bytes()).hexdigest()
    if digest != LABELS_SHA256:
        print(
            f"FATAL: labels sha256 {digest} != Stage-B committed {LABELS_SHA256}",
            file=sys.stderr,
        )
        return 1

    labels = pd.read_parquet(args.labels)
    outcomes = pd.read_csv(args.outcomes, dtype={"brief_date": str, "ticker": str})
    joined = labels.merge(
        outcomes, on=["brief_date", "ticker"], how="left", suffixes=("", "_ladder")
    )
    if len(joined) != len(labels):
        print("FATAL: (brief_date, ticker) join is not 1:1", file=sys.stderr)
        return 1

    results: dict = {
        "labels_sha256": digest,
        "bootstrap": {"resamples": BOOTSTRAP_RESAMPLES, "seed": BOOTSTRAP_SEED},
        "attrition": {w: _attrition(joined, w) for w in ("CLEAN", "DEV", "EXCLUDED_CLEAN_DAY")},
    }

    clean = _matured_contrast(joined, "CLEAN")
    results["primary_clean"] = _contrast_stats(clean, winsor=True)
    results["primary_clean_unwinsorized"] = _contrast_stats(clean, winsor=False)

    dev = _matured_contrast(joined, "DEV")
    results["dev_descriptive"] = _contrast_stats(dev, winsor=True)
    results["dev_descriptive_unwinsorized"] = _contrast_stats(dev, winsor=False)

    results["crowd_out"] = _crowd_out(labels)
    taxonomy = _refusal_taxonomy(args.calls_log)
    results["refusal_taxonomy"] = {k: v for k, v in taxonomy.items() if k != "pair_buckets"}

    # Refusal rate at pair level (labeled contrast pairs, full cohort + CLEAN).
    pair_labels = labels.drop_duplicates("pair_id")
    contrast_pairs = pair_labels[pair_labels["pair_label"].isin(CONTRAST_LABELS)]
    clean_pairs = contrast_pairs[contrast_pairs["window"] == "CLEAN"]
    results["refusal_rate"] = {
        "cohort_pairs": len(contrast_pairs),
        "cohort_refused": int((contrast_pairs["pair_label"] == REFUSED).sum()),
        "clean_pairs": len(clean_pairs),
        "clean_refused": int((clean_pairs["pair_label"] == REFUSED).sum()),
    }

    # Phase-3 power inputs: CLEAN spread magnitude + pooled pair-level sd.
    delta_mag = abs(results["primary_clean"]["delta"])
    legs = results["primary_clean"]["legs"]
    sd_pool = math.sqrt(
        (
            (legs[KEPT]["n_pairs"] - 1) * legs[KEPT]["pair_sd"] ** 2
            + (legs[REFUSED]["n_pairs"] - 1) * legs[REFUSED]["pair_sd"] ** 2
        )
        / (legs[KEPT]["n_pairs"] + legs[REFUSED]["n_pairs"] - 2)
    )
    refusal_rate = (
        results["refusal_rate"]["cohort_refused"] / results["refusal_rate"]["cohort_pairs"]
    )
    power_grid = []
    for pairs_per_day in (1.0, 1.5, 2.0, 3.0, 4.5):
        for trading_days in (15, 30, 45, 60, 90):
            n_total = pairs_per_day * trading_days
            n_ref = n_total * refusal_rate
            n_kept = n_total - n_ref
            power_grid.append(
                {
                    "pairs_per_day": pairs_per_day,
                    "trading_days": trading_days,
                    "n_kept": round(n_kept, 1),
                    "n_refused": round(n_ref, 1),
                    "power_full_effect": round(
                        power_one_sided(delta_mag, sd_pool, n_kept, n_ref), 3
                    ),
                    "power_half_effect": round(
                        power_one_sided(delta_mag / 2.0, sd_pool, n_kept, n_ref), 3
                    ),
                }
            )
    results["power_memo"] = {
        "design_effect_magnitude": delta_mag,
        "pooled_pair_sd": sd_pool,
        "refusal_rate_pair_level": refusal_rate,
        "required_n_per_leg_full_effect": required_n_per_leg(delta_mag, sd_pool),
        "required_n_per_leg_half_effect": required_n_per_leg(delta_mag / 2.0, sd_pool),
        "grid": power_grid,
    }

    args.out.write_text(json.dumps(results, indent=2, default=str), encoding="utf-8")
    primary = results["primary_clean"]
    print(
        f"PRIMARY (CLEAN, winsorized): delta={primary['delta']:+.4f} "
        f"p_one_sided={primary['bootstrap']['p_one_sided_gt0']:.4f} "
        f"ci95=[{primary['bootstrap']['ci95'][0]:+.4f}, {primary['bootstrap']['ci95'][1]:+.4f}] "
        f"n_pairs KEPT={primary['legs'][KEPT]['n_pairs']} "
        f"REFUSED={primary['legs'][REFUSED]['n_pairs']}"
    )
    print(f"results -> {args.out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
