# Generated by Django 6.0.5 on 2026-06-04 12:25

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DayMetaLadderOutcome",
            fields=[
                ("brief_date", models.DateField(primary_key=True, serialize=False)),
                ("n_rows", models.IntegerField()),
                ("n_plannable", models.IntegerField()),
                ("n_terminal", models.IntegerField()),
                ("parquet_mtime", models.FloatField()),
                ("rebuilt_at", models.DateTimeField()),
            ],
            options={
                "ordering": ["-brief_date"],
            },
        ),
        migrations.CreateModel(
            name="LadderOutcome",
            fields=[
                (
                    "pk",
                    models.CompositePrimaryKey(
                        "brief_date",
                        "ticker",
                        blank=True,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("brief_date", models.DateField(db_index=True)),
                ("ticker", models.CharField(max_length=12)),
                ("plannable", models.BooleanField(default=False)),
                ("nonplannable_reason", models.CharField(blank=True, default="", max_length=256)),
                ("terminal", models.BooleanField(default=False)),
                ("matured_at", models.DateField(blank=True, null=True)),
                ("ladder_classification", models.CharField(blank=True, default="", max_length=32)),
                ("blended_entry", models.FloatField(blank=True, null=True)),
                ("realized_r", models.FloatField(blank=True, null=True)),
                ("open_r", models.FloatField(blank=True, null=True)),
                ("mfe", models.FloatField(blank=True, null=True)),
                ("mae", models.FloatField(blank=True, null=True)),
                ("mfe_pct", models.FloatField(blank=True, null=True)),
                ("mae_pct", models.FloatField(blank=True, null=True)),
                ("forward_return", models.FloatField(blank=True, null=True)),
                ("benchmark_window_return", models.FloatField(blank=True, null=True)),
                ("market_excess_return", models.FloatField(blank=True, null=True)),
                ("sequence_str", models.CharField(blank=True, default="", max_length=256)),
                ("ambiguous_bars", models.IntegerField(blank=True, null=True)),
                ("ratchet_realized_r", models.FloatField(blank=True, null=True)),
                ("holding_days_elapsed", models.IntegerField(blank=True, null=True)),
                ("entry_ttl_days", models.IntegerField(blank=True, null=True)),
                ("position_ttl_days", models.IntegerField(blank=True, null=True)),
                ("suggested_gross_weight_pct", models.FloatField(blank=True, null=True)),
                ("full_ladder_blended_entry", models.FloatField(blank=True, null=True)),
                ("stop_distance_pct_full", models.FloatField(blank=True, null=True)),
                ("implied_risk_pct_full", models.FloatField(blank=True, null=True)),
                ("tiers_filled_count", models.FloatField(blank=True, null=True)),
                ("realized_gross_weight_pct", models.FloatField(blank=True, null=True)),
                ("stop_distance_pct", models.FloatField(blank=True, null=True)),
                ("realized_risk_pct", models.FloatField(blank=True, null=True)),
                ("realized_return_pct_of_book", models.FloatField(blank=True, null=True)),
                ("open_return_pct_of_book", models.FloatField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-brief_date", "ticker"],
                "indexes": [
                    models.Index(fields=["-brief_date", "ticker"], name="ladder_date_ticker_idx"),
                    models.Index(fields=["terminal"], name="ladder_terminal_idx"),
                ],
            },
        ),
    ]
