# Generated by Django 6.0.6 on 2026-06-09 09:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("edge", "0002_ladderoutcome_theme"),
    ]

    operations = [
        migrations.AddField(
            model_name="ladderoutcome",
            name="chart_payload_json",
            field=models.TextField(blank=True, default=""),
        ),
    ]
