# Generated by Django 6.0.6 on 2026-06-11 15:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("edge", "0003_ladderoutcome_chart_payload_json"),
    ]

    operations = [
        migrations.AddField(
            model_name="ladderoutcome",
            name="ladder_config_version",
            field=models.CharField(blank=True, default="", max_length=256),
        ),
    ]
