# Generated by Django 6.0.6 on 2026-06-11 15:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("edge", "0004_ladderoutcome_ladder_config_version"),
    ]

    operations = [
        migrations.AddField(
            model_name="ladderoutcome",
            name="grid_realized_r_json",
            field=models.TextField(blank=True, default=""),
        ),
    ]
