# Generated by Django 6.0.6 on 2026-06-11 16:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("edge", "0005_ladderoutcome_grid_realized_r_json"),
    ]

    operations = [
        migrations.AddField(
            model_name="ladderoutcome",
            name="realized_r_full_fill",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
