# Generated by Django 6.0.6 on 2026-06-25 14:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("edge", "0006_ladderoutcome_realized_r_full_fill"),
    ]

    operations = [
        migrations.AddField(
            model_name="ladderoutcome",
            name="scorer_config_version",
            field=models.CharField(blank=True, default="", max_length=128),
        ),
    ]
