# Generated by Django 6.0.6 on 2026-06-30 19:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("edge", "0007_ladderoutcome_scorer_config_version"),
    ]

    operations = [
        migrations.AddField(
            model_name="ladderoutcome",
            name="breakeven_realized_r_json",
            field=models.TextField(blank=True, default=""),
        ),
    ]
