# Generated by Django 6.0.7 on 2026-07-18 10:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("edge", "0009_ladderoutcome_outcome_benchmark_version_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ladderoutcome",
            name="captured_tp_count",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ladderoutcome",
            name="touched_tp_count",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
