/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/candidates/{date}/{ticker}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description ``/v1/candidates/{date}/{ticker}`` — single candidate fetch.
         *
         *     The detail PK is supplied as a compound URL segment, not a single field.
         *     The router pattern in ``urls.py`` is custom for this reason.
         */
        get: operations["v1_candidates_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/days": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description ``/v1/days`` — index + per-day envelope + per-day candidates. */
        get: operations["v1_days_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/days/{date}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description ``/v1/days`` — index + per-day envelope + per-day candidates. */
        get: operations["v1_days_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/days/{date}/candidates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description ``/v1/days`` — index + per-day envelope + per-day candidates. */
        get: operations["v1_days_candidates_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/edge/chart/{brief_date}/{ticker}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description ``/v1/edge/chart/<brief_date>/<ticker>`` — the pre-computed chart payload. */
        get: operations["v1_edge_chart_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/edge/outcomes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description ``/v1/edge/outcomes`` — per-candidate rows (theme joined from the brief). */
        get: operations["v1_edge_outcomes_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/edge/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description ``/v1/edge/summary`` — the N-gated, benchmark-relative aggregate. */
        get: operations["v1_edge_summary_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/market/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Current market-status snapshot
         * @description Returns whether the requested venue (defaulting to XNYS) holds a session on the anchor date, whether that session is a half-day, whether the venue is in a regular session right now, and the UTC ISO 8601 timestamps of the next session open and next session close. The day-level fields (``is_trading_day``, ``is_half_day``, ``next_open_iso``) are anchored on UTC today unless ``?as_of=YYYY-MM-DD`` is supplied; the intraday fields (``is_open_now``, ``next_close_iso``) always reflect the current wall-clock instant.
         */
        get: operations["market_status_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description ``/v1/stats`` — top-line counters + N most-frequent themes. */
        get: operations["v1_stats_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/themes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description ``/v1/themes`` — distinct-theme aggregation + per-theme candidates. */
        get: operations["v1_themes_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/themes/{theme}/candidates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description ``/v1/themes`` — distinct-theme aggregation + per-theme candidates. */
        get: operations["v1_themes_candidates_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/tickers/{ticker}/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description ``/v1/tickers/{ticker}/history`` — every brief appearance for one ticker. */
        get: operations["v1_tickers_history_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description One ranked candidate for a BULK list (day brief / theme / ticker history).
         *
         *     Auto-exposes every Brief field except the composite pk — INCLUDING the
         *     ``expert_assessments`` blob, which the SPA card reads (PR-5a). The *_str legacy
         *     denormalisations live only in DRF method fields, not on the model, so they are
         *     not auto-exposed here.
         */
        Candidate: {
            /** Format: date */
            date: string;
            ticker: string;
            theme: string;
            company_name: string;
            rationale?: string;
            /** Format: double */
            llm_confidence?: number | null;
            /** Format: double */
            market_cap?: number | null;
            gates_passed?: unknown;
            /** Format: int64 */
            n_gates_passed?: number;
            gates_failed?: unknown;
            /** Format: int64 */
            n_gates_failed?: number;
            gates_unknown?: unknown;
            /** Format: int64 */
            n_gates_unknown?: number;
            verified?: boolean;
            gate_verdict_json?: string;
            /** Format: uri */
            source_event_url?: string;
            source_event_title?: string;
            source_event_published_at?: string;
            theme_search_keywords?: unknown;
            /** Format: double */
            industry_id?: number | null;
            industry_name?: string;
            sector_name?: string;
            peer_cohort_level?: string;
            /** Format: double */
            insider_score_usd?: number | null;
            /** Format: double */
            insider_score_sector_percentile?: number | null;
            /** Format: double */
            fcff_yield_pct?: number | null;
            /** Format: double */
            fcff_yield_sector_percentile?: number | null;
            /** Format: double */
            valuation_pe?: number | null;
            /** Format: double */
            valuation_ps?: number | null;
            /** Format: double */
            valuation_ev_rev?: number | null;
            /** Format: double */
            valuation_ev_ebitda?: number | null;
            /** Format: double */
            valuation_fcf_margin?: number | null;
            /** Format: double */
            valuation_composite_sector_percentile?: number | null;
            valuation_financials_publish_date?: string;
            /** Format: int64 */
            valuation_financials_age_days?: number | null;
            /** Format: double */
            roic_pct?: number | null;
            /** Format: double */
            roe_pct?: number | null;
            magic_formula_health_pass?: boolean;
            /** Format: double */
            buffett_owner_earnings_yield_pct?: number | null;
            /** Format: double */
            buffett_roic_latest?: number | null;
            /** Format: double */
            buffett_roic_3y_avg?: number | null;
            /** Format: double */
            buffett_margin_of_safety_pct?: number | null;
            /** Format: double */
            buffett_data_coverage?: number | null;
            /** Format: double */
            buffett_quality_score?: number | null;
            buffett_moat_type?: string;
            buffett_moat_trend?: string;
            buffett_management_candor?: string;
            buffett_understandable?: boolean | null;
            buffett_qualitative_rationale?: string;
            buffett_used_scuttlebutt?: boolean | null;
            buffett_qual_computed_at?: string;
            expert_assessments?: unknown;
            /** Format: double */
            technical_rsi?: number | null;
            /** Format: double */
            technical_ma50_distance_pct?: number | null;
            /** Format: double */
            technical_atr_pct?: number | null;
            /** Format: double */
            technical_volume_zscore?: number | null;
            /** Format: double */
            technical_pct_off_52w_high?: number | null;
            /** Format: double */
            technical_pct_off_52w_low?: number | null;
            /** Format: double */
            technical_ma200_distance_pct?: number | null;
            /** Format: double */
            technical_ma200_slope_pct_per_day?: number | null;
            /** Format: double */
            catalyst_strength?: number | null;
            catalyst_event_type?: string;
            /** Format: double */
            catalyst_confidence?: number | null;
            /** Format: double */
            magic_formula_rank?: number | null;
            /** Format: int64 */
            magic_formula_cohort_n?: number | null;
            deep_drawdown_reversal?: boolean;
            /** Format: int64 */
            layer4_weighted_score?: number;
            also_in_themes?: unknown;
            /** Format: int64 */
            rank_in_day?: number | null;
            /** Format: int64 */
            cohort_size_in_day?: number | null;
            /** Format: date */
            next_earnings_date?: string | null;
            brief_model_used?: string;
            brief_tldr?: string;
            brief_supply_chain_md?: string;
            brief_bear_summary_md?: string;
            brief_catalyst_failure_exit?: string;
            brief_trade_setup?: unknown;
            brief_template_id?: string;
            brief_template_facts?: unknown;
            /** Format: date-time */
            brief_generated_at?: string | null;
        };
        /**
         * @description One candidate for the single-candidate DETAIL endpoint
         *     (``/v1/candidates/{date}/{ticker}``). Identical to :class:`CandidateSerializer`
         *     today; kept distinct so a future N-expert payload-split can trim the bulk list
         *     again without re-touching the endpoint wiring.
         */
        CandidateDetail: {
            /** Format: date */
            date: string;
            ticker: string;
            theme: string;
            company_name: string;
            rationale?: string;
            /** Format: double */
            llm_confidence?: number | null;
            /** Format: double */
            market_cap?: number | null;
            gates_passed?: unknown;
            /** Format: int64 */
            n_gates_passed?: number;
            gates_failed?: unknown;
            /** Format: int64 */
            n_gates_failed?: number;
            gates_unknown?: unknown;
            /** Format: int64 */
            n_gates_unknown?: number;
            verified?: boolean;
            gate_verdict_json?: string;
            /** Format: uri */
            source_event_url?: string;
            source_event_title?: string;
            source_event_published_at?: string;
            theme_search_keywords?: unknown;
            /** Format: double */
            industry_id?: number | null;
            industry_name?: string;
            sector_name?: string;
            peer_cohort_level?: string;
            /** Format: double */
            insider_score_usd?: number | null;
            /** Format: double */
            insider_score_sector_percentile?: number | null;
            /** Format: double */
            fcff_yield_pct?: number | null;
            /** Format: double */
            fcff_yield_sector_percentile?: number | null;
            /** Format: double */
            valuation_pe?: number | null;
            /** Format: double */
            valuation_ps?: number | null;
            /** Format: double */
            valuation_ev_rev?: number | null;
            /** Format: double */
            valuation_ev_ebitda?: number | null;
            /** Format: double */
            valuation_fcf_margin?: number | null;
            /** Format: double */
            valuation_composite_sector_percentile?: number | null;
            valuation_financials_publish_date?: string;
            /** Format: int64 */
            valuation_financials_age_days?: number | null;
            /** Format: double */
            roic_pct?: number | null;
            /** Format: double */
            roe_pct?: number | null;
            magic_formula_health_pass?: boolean;
            /** Format: double */
            buffett_owner_earnings_yield_pct?: number | null;
            /** Format: double */
            buffett_roic_latest?: number | null;
            /** Format: double */
            buffett_roic_3y_avg?: number | null;
            /** Format: double */
            buffett_margin_of_safety_pct?: number | null;
            /** Format: double */
            buffett_data_coverage?: number | null;
            /** Format: double */
            buffett_quality_score?: number | null;
            buffett_moat_type?: string;
            buffett_moat_trend?: string;
            buffett_management_candor?: string;
            buffett_understandable?: boolean | null;
            buffett_qualitative_rationale?: string;
            buffett_used_scuttlebutt?: boolean | null;
            buffett_qual_computed_at?: string;
            expert_assessments?: unknown;
            /** Format: double */
            technical_rsi?: number | null;
            /** Format: double */
            technical_ma50_distance_pct?: number | null;
            /** Format: double */
            technical_atr_pct?: number | null;
            /** Format: double */
            technical_volume_zscore?: number | null;
            /** Format: double */
            technical_pct_off_52w_high?: number | null;
            /** Format: double */
            technical_pct_off_52w_low?: number | null;
            /** Format: double */
            technical_ma200_distance_pct?: number | null;
            /** Format: double */
            technical_ma200_slope_pct_per_day?: number | null;
            /** Format: double */
            catalyst_strength?: number | null;
            catalyst_event_type?: string;
            /** Format: double */
            catalyst_confidence?: number | null;
            /** Format: double */
            magic_formula_rank?: number | null;
            /** Format: int64 */
            magic_formula_cohort_n?: number | null;
            deep_drawdown_reversal?: boolean;
            /** Format: int64 */
            layer4_weighted_score?: number;
            also_in_themes?: unknown;
            /** Format: int64 */
            rank_in_day?: number | null;
            /** Format: int64 */
            cohort_size_in_day?: number | null;
            /** Format: date */
            next_earnings_date?: string | null;
            brief_model_used?: string;
            brief_tldr?: string;
            brief_supply_chain_md?: string;
            brief_bear_summary_md?: string;
            brief_catalyst_failure_exit?: string;
            brief_trade_setup?: unknown;
            brief_template_id?: string;
            brief_template_facts?: unknown;
            /** Format: date-time */
            brief_generated_at?: string | null;
        };
        /**
         * @description One daily OHLC candle (folded from the cached minute bars, RTH-only).
         *
         *     ``time`` is an ISO date string (``YYYY-MM-DD``) so it maps 1:1 to a
         *     Lightweight-Charts daily bar time.
         */
        ChartBar: {
            time: string;
            /** Format: double */
            open: number;
            /** Format: double */
            high: number;
            /** Format: double */
            low: number;
            /** Format: double */
            close: number;
            /** Format: double */
            volume: number;
        };
        /**
         * @description One modeled fill / exit marker, snapped to a daily bar ``time``.
         *
         *     ``kind`` is the chart vocabulary (``ENTRY`` / ``TP`` / ``SL`` / ``TIME_STOP``);
         *     ``ambiguous`` carries the SL-first intrabar flag (a bar that touched both a TP
         *     high and the SL low, resolved SL-first).
         */
        ChartMarker: {
            time: string;
            kind: string;
            level_id: string;
            /** Format: double */
            price: number | null;
            label: string;
            ambiguous: boolean;
        };
        /**
         * @description The resting ladder levels drawn as horizontal price lines.
         *
         *     ``tp`` is the ordered list of take-profit targets. TIME_STOP is NOT a price
         *     line — it is an exit event drawn only as a marker.
         */
        ChartPriceLines: {
            /** Format: double */
            entry: number | null;
            tp: number[];
            /** Format: double */
            stop: number | null;
        };
        /**
         * @description ``/v1/edge/chart/<brief_date>/<ticker>`` — the pre-computed chart payload.
         *
         *     The SHAPE is stable across ``status``: a NO_DATA / NO_STRUCTURE payload carries
         *     empty ``bars`` / ``markers`` and null/empty ``price_lines`` so the SPA branches
         *     on ``status`` without a 2nd request. ``rth_only`` is always true in PR-1
         *     (RTH-only daily candles; intraday is a later PR).
         */
        ChartResponse: {
            /** Format: date */
            brief_date: string;
            ticker: string;
            ladder_classification: string;
            terminal: boolean;
            holding_days_elapsed: number | null;
            /** Format: double */
            open_r: number | null;
            /** Format: double */
            realized_r: number | null;
            status: components["schemas"]["ChartResponseStatusEnum"];
            bars: components["schemas"]["ChartBar"][];
            price_lines: components["schemas"]["ChartPriceLines"];
            markers: components["schemas"]["ChartMarker"][];
            ambiguous_bars: number;
            intrabar_rule: string;
            rth_only: boolean;
        };
        /**
         * @description * `OK` - OK
         *     * `NO_DATA` - NO_DATA
         *     * `NO_STRUCTURE` - NO_STRUCTURE
         * @enum {string}
         */
        ChartResponseStatusEnum: "OK" | "NO_DATA" | "NO_STRUCTURE";
        /** @description Full payload for one day: meta + every ranked candidate. */
        DayBrief: {
            /** Format: date */
            date: string;
            n_candidates: number;
            n_themes: number;
            top_theme: string | null;
            theme_counts: {
                [key: string]: number;
            };
            candidates: components["schemas"]["Candidate"][];
        };
        /** @description Row in ``/v1/days``: per-day metadata only (no candidates). */
        DayMeta: {
            /** Format: date */
            date: string;
            /** Format: int64 */
            n_candidates: number;
            /** Format: int64 */
            n_themes: number;
            /** @description Empty-string DB default → None on the wire (parity with legacy API). */
            readonly top_theme: string | null;
        };
        /** @description The DEPLOYMENT panel — N-INDEPENDENT, always populated. */
        DeploymentPanel: {
            n_terminal: number;
            n_filled: number;
            n_no_fill: number;
            /** Format: double */
            fill_rate: number | null;
            /** Format: double */
            no_fill_rate: number | null;
            /** Format: double */
            mean_tiers_filled_count: number | null;
        };
        /** @description The lean per-candidate shape for ``/v1/edge/outcomes`` (memo §5 table). */
        EdgeOutcomeRow: {
            ticker: string;
            /** Format: date */
            brief_date: string;
            theme?: string | null;
            ladder_classification: string;
            terminal: boolean;
            /** Format: double */
            realized_r: number | null;
            /** Format: double */
            open_r: number | null;
            /** Format: double */
            market_excess_return: number | null;
            /** Format: double */
            forward_return: number | null;
            /** Format: double */
            benchmark_window_return: number | null;
            holding_days_elapsed: number | null;
            /** Format: double */
            realized_return_pct_of_book: number | null;
        };
        /**
         * @description The EDGE panel — gated. ``status='insufficient'`` nulls the stat fields.
         *
         *     The key SHAPE is stable (every field always present); the N-gate hides the
         *     numbers by setting them to ``null`` rather than dropping the keys, so the
         *     frontend can build a single static type and branch on ``status``.
         */
        EdgePanel: {
            status: components["schemas"]["Status3b9Enum"];
            n_matured: number;
            threshold: number;
            /** Format: double */
            market_excess_mean: number | null;
            /** Format: double */
            market_excess_median: number | null;
            market_excess_quantiles: components["schemas"]["_Quantiles"];
            /** Format: double */
            gross_realized_r_mean: number | null;
            /** Format: double */
            gross_realized_r_median: number | null;
            gross_realized_r_n: number;
            holding_days_n: number;
            /** Format: double */
            holding_days_p50: number | null;
            /** Format: double */
            holding_days_p95: number | null;
            gross_of_cost: boolean;
            regime_stratified: boolean;
        };
        /** @description ``/v1/edge/summary`` — the full N-gated, benchmark-relative aggregate. */
        EdgeSummary: {
            n_brief: number;
            n_plannable: number;
            n_terminal: number;
            n_matured: number;
            n_gate_threshold: number;
            benchmark: string;
            metric_note: string;
            edge: components["schemas"]["EdgePanel"];
            portfolio: components["schemas"]["PortfolioPanel"];
            deployment: components["schemas"]["DeploymentPanel"];
            open_positions: components["schemas"]["OpenPositions"];
        };
        MarketStatus: {
            is_trading_day: boolean;
            is_half_day: boolean;
            is_open_now: boolean;
            /** Format: date-time */
            next_open_iso: string;
            /** Format: date-time */
            next_close_iso: string;
            exchange: string;
        };
        /** @description Ongoing positions as a DESCRIPTIVE distribution (never a scalar mean). */
        OpenPositions: {
            n_open: number;
            near_tp: number;
            near_sl: number;
            note: string;
        };
        PaginatedCandidateList: {
            data: components["schemas"]["Candidate"][];
            meta: {
                /** @example 123 */
                total: number;
                /** @example 50 */
                limit: number;
                /** @example 0 */
                offset: number;
            };
        };
        PaginatedDayMetaList: {
            data: components["schemas"]["DayMeta"][];
            meta: {
                /** @example 123 */
                total: number;
                /** @example 50 */
                limit: number;
                /** @example 0 */
                offset: number;
            };
        };
        PaginatedThemeSummaryList: {
            data: components["schemas"]["ThemeSummary"][];
            meta: {
                /** @example 123 */
                total: number;
                /** @example 50 */
                limit: number;
                /** @example 0 */
                offset: number;
            };
        };
        /** @description The PORTFOLIO (size-weighted) panel — gated, same N-gate as EDGE. */
        PortfolioPanel: {
            status: components["schemas"]["Status3b9Enum"];
            n_matured: number;
            threshold: number;
            /** Format: double */
            total_realized_contribution_pct_of_book: number | null;
            /** Format: double */
            size_weighted_realized_r: number | null;
            /** Format: double */
            mean_realized_risk_pct: number | null;
            /** Format: double */
            mean_tiers_filled_count: number | null;
            gross_of_cost: boolean;
        };
        /** @description Top-line counters and most-frequent themes for ``/v1/stats``. */
        Stats: {
            n_days: number;
            n_candidates: number;
            n_themes: number;
            /** Format: date */
            earliest_date: string | null;
            /** Format: date */
            latest_date: string | null;
            /** Format: date-time */
            last_rebuild_at: string | null;
            top_themes: components["schemas"]["TopTheme"][];
        };
        /**
         * @description * `insufficient` - insufficient
         *     * `early` - early
         *     * `ok` - ok
         * @enum {string}
         */
        Status3b9Enum: "insufficient" | "early" | "ok";
        /** @description Row in ``/v1/themes``: distinct theme + appearance counts. */
        ThemeSummary: {
            theme: string;
            n_candidates: number;
            n_days: number;
            /** Format: date */
            first_seen: string;
            /** Format: date */
            last_seen: string;
        };
        TopTheme: {
            theme: string;
            n_days: number;
            n_candidates: number;
        };
        _Quantiles: {
            /** Format: double */
            p10: number | null;
            /** Format: double */
            p50: number | null;
            /** Format: double */
            p90: number | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    v1_candidates_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                date: string;
                ticker: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CandidateDetail"];
                };
            };
        };
    };
    v1_days_list: {
        parameters: {
            query?: {
                /** @description Inclusive ISO date lower bound. */
                from?: string;
                /** @description Number of results to return per page. */
                limit?: number;
                /** @description The initial index from which to return the results. */
                offset?: number;
                /** @description Inclusive ISO date upper bound. */
                to?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedDayMetaList"];
                };
            };
        };
    };
    v1_days_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ISO 8601 date (YYYY-MM-DD). */
                date: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DayBrief"];
                };
            };
        };
    };
    v1_days_candidates_list: {
        parameters: {
            query?: {
                /** @description Number of results to return per page. */
                limit?: number;
                /** @description Layer-4 score floor. */
                min_score?: number;
                /** @description The initial index from which to return the results. */
                offset?: number;
                /** @description Exact theme match. */
                theme?: string;
            };
            header?: never;
            path: {
                /** @description ISO 8601 date (YYYY-MM-DD). */
                date: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedCandidateList"];
                };
            };
        };
    };
    v1_edge_chart_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Brief date (ISO YYYY-MM-DD). */
                brief_date: string;
                /** @description Candidate ticker (case-insensitive). */
                ticker: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChartResponse"];
                };
            };
        };
    };
    v1_edge_outcomes_list: {
        parameters: {
            query?: {
                /** @description Filter: 'terminal' or 'ongoing' (default: all plannable). */
                status?: string;
                /** @description Calendar days back from the latest brief date (default: all). */
                window?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EdgeOutcomeRow"][];
                };
            };
        };
    };
    v1_edge_summary_retrieve: {
        parameters: {
            query?: {
                /** @description Calendar days back from the latest brief date (default: all). */
                window?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EdgeSummary"];
                };
            };
        };
    };
    market_status_retrieve: {
        parameters: {
            query?: {
                /** @description ISO 8601 date (YYYY-MM-DD) to anchor the response on. Defaults to today (UTC). Date-only — time components are rejected with 400. */
                as_of?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MarketStatus"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    v1_stats_retrieve: {
        parameters: {
            query?: {
                /** @description Top themes to include (1-50). */
                top_n?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Stats"];
                };
            };
        };
    };
    v1_themes_list: {
        parameters: {
            query?: {
                /** @description Inclusive ISO date lower bound. */
                from?: string;
                /** @description Number of results to return per page. */
                limit?: number;
                /** @description The initial index from which to return the results. */
                offset?: number;
                /** @description Inclusive ISO date upper bound. */
                to?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedThemeSummaryList"];
                };
            };
        };
    };
    v1_themes_candidates_list: {
        parameters: {
            query?: {
                /** @description Inclusive ISO date lower bound. */
                from?: string;
                /** @description Number of results to return per page. */
                limit?: number;
                /** @description The initial index from which to return the results. */
                offset?: number;
                /** @description Inclusive ISO date upper bound. */
                to?: string;
            };
            header?: never;
            path: {
                /** @description Exact theme name. */
                theme: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedCandidateList"];
                };
            };
        };
    };
    v1_tickers_history_list: {
        parameters: {
            query?: {
                /** @description Inclusive ISO date lower bound. */
                from?: string;
                /** @description Number of results to return per page. */
                limit?: number;
                /** @description The initial index from which to return the results. */
                offset?: number;
                /** @description Inclusive ISO date upper bound. */
                to?: string;
            };
            header?: never;
            path: {
                /** @description Upper-case ticker symbol. */
                ticker: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedCandidateList"];
                };
            };
        };
    };
}
