/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/candidates/{date}/{ticker}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description ``/v1/candidates/{date}/{ticker}`` — single candidate fetch.
         *
         *     The detail PK is supplied as a compound URL segment, not a single field.
         *     The router pattern in ``urls.py`` is custom for this reason.
         */
        get: operations["v1_candidates_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/days": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description ``/v1/days`` — index + per-day envelope + per-day candidates. */
        get: operations["v1_days_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/days/{date}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description ``/v1/days`` — index + per-day envelope + per-day candidates. */
        get: operations["v1_days_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/days/{date}/candidates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description ``/v1/days`` — index + per-day envelope + per-day candidates. */
        get: operations["v1_days_candidates_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/edge/outcomes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description ``/v1/edge/outcomes`` — per-candidate rows (theme joined from the brief). */
        get: operations["v1_edge_outcomes_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/edge/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description ``/v1/edge/summary`` — the N-gated, benchmark-relative aggregate. */
        get: operations["v1_edge_summary_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/market/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Current market-status snapshot
         * @description Returns whether the requested venue (defaulting to XNYS) is currently in a regular session, whether today's session is a half-day, and the UTC ISO 8601 timestamp of the next session open. Anchored on UTC today unless ``?as_of=YYYY-MM-DD`` is supplied.
         */
        get: operations["market_status_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description ``/v1/stats`` — top-line counters + N most-frequent themes. */
        get: operations["v1_stats_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/themes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description ``/v1/themes`` — distinct-theme aggregation + per-theme candidates. */
        get: operations["v1_themes_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/themes/{theme}/candidates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description ``/v1/themes`` — distinct-theme aggregation + per-theme candidates. */
        get: operations["v1_themes_candidates_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/tickers/{ticker}/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description ``/v1/tickers/{ticker}/history`` — every brief appearance for one ticker. */
        get: operations["v1_tickers_history_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description One ranked candidate from a daily thematic brief. */
        Candidate: {
            /** Format: date */
            date: string;
            ticker: string;
            theme: string;
            company_name: string;
            rationale?: string;
            /** Format: double */
            llm_confidence?: number | null;
            /** Format: double */
            market_cap?: number | null;
            gates_passed?: unknown;
            /** Format: int64 */
            n_gates_passed?: number;
            gates_failed?: unknown;
            /** Format: int64 */
            n_gates_failed?: number;
            gates_unknown?: unknown;
            /** Format: int64 */
            n_gates_unknown?: number;
            verified?: boolean;
            /** Format: uri */
            source_event_url?: string;
            source_event_title?: string;
            source_event_published_at?: string;
            theme_search_keywords?: unknown;
            /** Format: double */
            industry_id?: number | null;
            industry_name?: string;
            sector_name?: string;
            peer_cohort_level?: string;
            /** Format: double */
            insider_score_usd?: number | null;
            /** Format: double */
            insider_score_sector_percentile?: number | null;
            /** Format: double */
            fcff_yield_pct?: number | null;
            /** Format: double */
            fcff_yield_sector_percentile?: number | null;
            /** Format: double */
            valuation_pe?: number | null;
            /** Format: double */
            valuation_ps?: number | null;
            /** Format: double */
            valuation_ev_rev?: number | null;
            /** Format: double */
            valuation_ev_ebitda?: number | null;
            /** Format: double */
            valuation_fcf_margin?: number | null;
            /** Format: double */
            valuation_composite_sector_percentile?: number | null;
            valuation_financials_publish_date?: string;
            /** Format: int64 */
            valuation_financials_age_days?: number | null;
            /** Format: double */
            roic_pct?: number | null;
            /** Format: double */
            roe_pct?: number | null;
            magic_formula_health_pass?: boolean;
            /** Format: double */
            technical_rsi?: number | null;
            /** Format: double */
            technical_ma50_distance_pct?: number | null;
            /** Format: double */
            technical_atr_pct?: number | null;
            /** Format: double */
            technical_volume_zscore?: number | null;
            /** Format: double */
            technical_pct_off_52w_high?: number | null;
            /** Format: double */
            technical_pct_off_52w_low?: number | null;
            /** Format: double */
            technical_ma200_distance_pct?: number | null;
            /** Format: double */
            technical_ma200_slope_pct_per_day?: number | null;
            /** Format: double */
            catalyst_strength?: number | null;
            catalyst_event_type?: string;
            /** Format: double */
            catalyst_confidence?: number | null;
            /** Format: double */
            magic_formula_rank?: number | null;
            /** Format: int64 */
            magic_formula_cohort_n?: number | null;
            deep_drawdown_reversal?: boolean;
            /** Format: int64 */
            layer4_weighted_score?: number;
            also_in_themes?: unknown;
            /** Format: int64 */
            rank_in_day?: number | null;
            /** Format: int64 */
            cohort_size_in_day?: number | null;
            /** Format: date */
            next_earnings_date?: string | null;
            brief_model_used?: string;
            brief_tldr?: string;
            brief_supply_chain_md?: string;
            brief_bear_summary_md?: string;
            brief_catalyst_failure_exit?: string;
            brief_trade_setup?: unknown;
            brief_template_id?: string;
            brief_template_facts?: unknown;
            /** Format: date-time */
            brief_generated_at?: string | null;
        };
        /** @description Full payload for one day: meta + every ranked candidate. */
        DayBrief: {
            /** Format: date */
            date: string;
            n_candidates: number;
            n_themes: number;
            top_theme: string | null;
            theme_counts: {
                [key: string]: number;
            };
            candidates: components["schemas"]["Candidate"][];
        };
        /** @description Row in ``/v1/days``: per-day metadata only (no candidates). */
        DayMeta: {
            /** Format: date */
            date: string;
            /** Format: int64 */
            n_candidates: number;
            /** Format: int64 */
            n_themes: number;
            /** @description Empty-string DB default → None on the wire (parity with legacy API). */
            readonly top_theme: string | null;
        };
        /** @description The DEPLOYMENT panel — N-INDEPENDENT, always populated. */
        DeploymentPanel: {
            n_terminal: number;
            n_filled: number;
            n_no_fill: number;
            /** Format: double */
            fill_rate: number | null;
            /** Format: double */
            no_fill_rate: number | null;
            /** Format: double */
            mean_tiers_filled_count: number | null;
        };
        /** @description The lean per-candidate shape for ``/v1/edge/outcomes`` (memo §5 table). */
        EdgeOutcomeRow: {
            ticker: string;
            /** Format: date */
            brief_date: string;
            theme?: string | null;
            ladder_classification: string;
            terminal: boolean;
            /** Format: double */
            realized_r: number | null;
            /** Format: double */
            open_r: number | null;
            /** Format: double */
            market_excess_return: number | null;
            /** Format: double */
            forward_return: number | null;
            /** Format: double */
            benchmark_window_return: number | null;
            holding_days_elapsed: number | null;
            /** Format: double */
            realized_return_pct_of_book: number | null;
        };
        /**
         * @description The EDGE panel — gated. ``status='insufficient'`` nulls the stat fields.
         *
         *     The key SHAPE is stable (every field always present); the N-gate hides the
         *     numbers by setting them to ``null`` rather than dropping the keys, so the
         *     frontend can build a single static type and branch on ``status``.
         */
        EdgePanel: {
            status: components["schemas"]["StatusEnum"];
            n_matured: number;
            threshold: number;
            /** Format: double */
            market_excess_mean: number | null;
            /** Format: double */
            market_excess_median: number | null;
            market_excess_quantiles: components["schemas"]["_Quantiles"];
            /** Format: double */
            gross_realized_r_mean: number | null;
            /** Format: double */
            gross_realized_r_median: number | null;
            gross_realized_r_n: number;
            holding_days_n: number;
            /** Format: double */
            holding_days_p50: number | null;
            /** Format: double */
            holding_days_p95: number | null;
            gross_of_cost: boolean;
            regime_stratified: boolean;
        };
        /** @description ``/v1/edge/summary`` — the full N-gated, benchmark-relative aggregate. */
        EdgeSummary: {
            n_brief: number;
            n_plannable: number;
            n_terminal: number;
            n_matured: number;
            n_gate_threshold: number;
            benchmark: string;
            metric_note: string;
            edge: components["schemas"]["EdgePanel"];
            portfolio: components["schemas"]["PortfolioPanel"];
            deployment: components["schemas"]["DeploymentPanel"];
            open_positions: components["schemas"]["OpenPositions"];
        };
        MarketStatus: {
            is_trading_day: boolean;
            is_half_day: boolean;
            /** Format: date-time */
            next_open_iso: string;
            exchange: string;
        };
        /** @description Ongoing positions as a DESCRIPTIVE distribution (never a scalar mean). */
        OpenPositions: {
            n_open: number;
            near_tp: number;
            near_sl: number;
            note: string;
        };
        PaginatedCandidateList: {
            data: components["schemas"]["Candidate"][];
            meta: {
                /** @example 123 */
                total: number;
                /** @example 50 */
                limit: number;
                /** @example 0 */
                offset: number;
            };
        };
        PaginatedDayMetaList: {
            data: components["schemas"]["DayMeta"][];
            meta: {
                /** @example 123 */
                total: number;
                /** @example 50 */
                limit: number;
                /** @example 0 */
                offset: number;
            };
        };
        PaginatedThemeSummaryList: {
            data: components["schemas"]["ThemeSummary"][];
            meta: {
                /** @example 123 */
                total: number;
                /** @example 50 */
                limit: number;
                /** @example 0 */
                offset: number;
            };
        };
        /** @description The PORTFOLIO (size-weighted) panel — gated, same N-gate as EDGE. */
        PortfolioPanel: {
            status: components["schemas"]["StatusEnum"];
            n_matured: number;
            threshold: number;
            /** Format: double */
            total_realized_contribution_pct_of_book: number | null;
            /** Format: double */
            size_weighted_realized_r: number | null;
            /** Format: double */
            mean_realized_risk_pct: number | null;
            /** Format: double */
            mean_tiers_filled_count: number | null;
            gross_of_cost: boolean;
        };
        /** @description Top-line counters and most-frequent themes for ``/v1/stats``. */
        Stats: {
            n_days: number;
            n_candidates: number;
            n_themes: number;
            /** Format: date */
            earliest_date: string | null;
            /** Format: date */
            latest_date: string | null;
            /** Format: date-time */
            last_rebuild_at: string | null;
            top_themes: components["schemas"]["TopTheme"][];
        };
        /**
         * @description * `insufficient` - insufficient
         *     * `early` - early
         *     * `ok` - ok
         * @enum {string}
         */
        StatusEnum: "insufficient" | "early" | "ok";
        /** @description Row in ``/v1/themes``: distinct theme + appearance counts. */
        ThemeSummary: {
            theme: string;
            n_candidates: number;
            n_days: number;
            /** Format: date */
            first_seen: string;
            /** Format: date */
            last_seen: string;
        };
        TopTheme: {
            theme: string;
            n_days: number;
            n_candidates: number;
        };
        _Quantiles: {
            /** Format: double */
            p10: number | null;
            /** Format: double */
            p50: number | null;
            /** Format: double */
            p90: number | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    v1_candidates_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                date: string;
                ticker: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Candidate"];
                };
            };
        };
    };
    v1_days_list: {
        parameters: {
            query?: {
                /** @description Inclusive ISO date lower bound. */
                from?: string;
                /** @description Number of results to return per page. */
                limit?: number;
                /** @description The initial index from which to return the results. */
                offset?: number;
                /** @description Inclusive ISO date upper bound. */
                to?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedDayMetaList"];
                };
            };
        };
    };
    v1_days_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ISO 8601 date (YYYY-MM-DD). */
                date: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DayBrief"];
                };
            };
        };
    };
    v1_days_candidates_list: {
        parameters: {
            query?: {
                /** @description Number of results to return per page. */
                limit?: number;
                /** @description Layer-4 score floor. */
                min_score?: number;
                /** @description The initial index from which to return the results. */
                offset?: number;
                /** @description Exact theme match. */
                theme?: string;
            };
            header?: never;
            path: {
                /** @description ISO 8601 date (YYYY-MM-DD). */
                date: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedCandidateList"];
                };
            };
        };
    };
    v1_edge_outcomes_list: {
        parameters: {
            query?: {
                /** @description Filter: 'terminal' or 'ongoing' (default: all plannable). */
                status?: string;
                /** @description Calendar days back from the latest brief date (default: all). */
                window?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EdgeOutcomeRow"][];
                };
            };
        };
    };
    v1_edge_summary_retrieve: {
        parameters: {
            query?: {
                /** @description Calendar days back from the latest brief date (default: all). */
                window?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EdgeSummary"];
                };
            };
        };
    };
    market_status_retrieve: {
        parameters: {
            query?: {
                /** @description ISO 8601 date (YYYY-MM-DD) to anchor the response on. Defaults to today (UTC). Date-only — time components are rejected with 400. */
                as_of?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MarketStatus"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    v1_stats_retrieve: {
        parameters: {
            query?: {
                /** @description Top themes to include (1-50). */
                top_n?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Stats"];
                };
            };
        };
    };
    v1_themes_list: {
        parameters: {
            query?: {
                /** @description Inclusive ISO date lower bound. */
                from?: string;
                /** @description Number of results to return per page. */
                limit?: number;
                /** @description The initial index from which to return the results. */
                offset?: number;
                /** @description Inclusive ISO date upper bound. */
                to?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedThemeSummaryList"];
                };
            };
        };
    };
    v1_themes_candidates_list: {
        parameters: {
            query?: {
                /** @description Inclusive ISO date lower bound. */
                from?: string;
                /** @description Number of results to return per page. */
                limit?: number;
                /** @description The initial index from which to return the results. */
                offset?: number;
                /** @description Inclusive ISO date upper bound. */
                to?: string;
            };
            header?: never;
            path: {
                /** @description Exact theme name. */
                theme: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedCandidateList"];
                };
            };
        };
    };
    v1_tickers_history_list: {
        parameters: {
            query?: {
                /** @description Inclusive ISO date lower bound. */
                from?: string;
                /** @description Number of results to return per page. */
                limit?: number;
                /** @description The initial index from which to return the results. */
                offset?: number;
                /** @description Inclusive ISO date upper bound. */
                to?: string;
            };
            header?: never;
            path: {
                /** @description Upper-case ticker symbol. */
                ticker: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedCandidateList"];
                };
            };
        };
    };
}
